CFLAGS   = -std=c11 -Wall -Wextra -O2

all: dragonshell

dragonshell: dragonshell.o jobstracker.o
	gcc $(CFLAGS) -o $@ $^

compile: dragonshell.o jobstracker.o

dragonshell.o: dragonshell.c jobstracker.h
	gcc -D_POSIX_C_SOURCE=200809L $(CFLAGS) -c $< -o $@

jobstracker.o: jobstracker.c jobstracker.h
	gcc -D_POSIX_C_SOURCE=200809L $(CFLAGS) -c $< -o $@

clean:
	rm -f dragonshell *.o